matrix:
  include:
  - language: node_js
    node_js: 12
    python: 3.8
    dist: bionic
    cache:
    - yarn: true
    - pip: true
    addons:
      sonarcloud:
        organization: "swsnu"
        token:
          secure: "CEkT0XfhvxWoN6dUgudjnd2ZkMMBpzxxrLHby+bP4cTJlIYRpALAttYqmvBokaSVcKOyiIG4RpS2qqSC1144VUeCA352W9O/u+EWNj2VKo66FA8jUbzb1vEh/Kbikj90SQ2kWp5HKQtaEDAdy/tWaoQk5VUYKDOMoxtMaDWv26M0dGx+pUXdMXpMCSteN3xTXNIJUdlqPktqaQyGTrBRGeTD09hVuEMVjAtreqAkcHrlzrb8sthPXuKXO8eIjU7xLBOdW/6yOFj/wHzRij7hM24hCFEBBnBni3a1M4GSFKoDUtY9R+K84ZZcH4i9q15wqf3LAffxKgYuBPt6ns1N8iVJGVvp+zdnohsoROVzy+h6cVedbER0x4OFlMXUeeB+yXDfIYz51pzu9DAb77pQc0H5GcSPCIlw5yNSLqNEEKvBRSvP3Pt11r3WHF1nXf3wXq93wxb/p8iHdJHVhz1F3IQ0W8UdS0q/CkIVUVVNH9G2jWS1iv/P+m6onkHpWLuPh/gpx/A1qh6WC7PXflVHS9kKDkgCtl9XlhnuaLmcBjaorrmFw9yrV+ZR18ZHJTzRtPLsdwvM1+itf2nEwC7K3QSHa4ZmnjAIlYOY12liR4HZKSdxNaaKSGz3GN3qqzbh4fbPqM5UaVEcyHN5taZwB/qH5sCgEz3jGkwIcZfFjmE="
    install:
    - cd frontend
    - yarn install
    - cd ../backend
    - source ~/virtualenv/python3.8/bin/activate
    - pip install -r requirements.txt
    - gem install coveralls-lcov
    script:
      - cd ../frontend
      - "./node_modules/.bin/eslint src/"
      - yarn test
      - coveralls-lcov -v -n coverage/lcov.info > coverage/coverage.json
      - cd ../backend
      - pylint **/*.py --exit-zero --load-plugins pylint_django
      - coverage run --branch --source='.' manage.py test && coverage report -m
      - coverage xml
      - cd ..
      - sonar-scanner
    after_success:
    - cd backend
    - coveralls --merge=../frontend/coverage/coverage.json
